# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_final/mb_final.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final || ORIG_REF_NAME==mb_final} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_clk_wiz_1_0/mb_final_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_clk_wiz_1_0 || ORIG_REF_NAME==mb_final_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_uartlite_0_0/mb_final_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_uartlite_0_0 || ORIG_REF_NAME==mb_final_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_timer_0_1/mb_final_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_timer_0_1 || ORIG_REF_NAME==mb_final_axi_timer_0_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_gpio_0_0/mb_final_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_gpio_0_0 || ORIG_REF_NAME==mb_final_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_quad_spi_0_0/mb_final_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_final_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_gpio_0_3/mb_final_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_gpio_0_3 || ORIG_REF_NAME==mb_final_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_gpio_0_4 || ORIG_REF_NAME==mb_final_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_1/mb_final_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_1 || ORIG_REF_NAME==mb_final_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_dlmb_v10_1/mb_final_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_dlmb_v10_1 || ORIG_REF_NAME==mb_final_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_ilmb_v10_1/mb_final_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_ilmb_v10_1 || ORIG_REF_NAME==mb_final_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_dlmb_bram_if_cntlr_1/mb_final_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_final_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_ilmb_bram_if_cntlr_1/mb_final_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_final_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_lmb_bram_1/mb_final_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_lmb_bram_1 || ORIG_REF_NAME==mb_final_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_xbar_1/mb_final_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_xbar_1 || ORIG_REF_NAME==mb_final_xbar_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_axi_periph_1/mb_final_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_final_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_axi_intc_1/mb_final_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_final_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_microblaze_0_xlconcat_0/mb_final_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_final_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_mdm_1_1/mb_final_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_mdm_1_1 || ORIG_REF_NAME==mb_final_mdm_1_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_rst_clk_wiz_1_100M_1/mb_final_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_final_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_axi_uartlite_1_0/mb_final_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_axi_uartlite_1_0 || ORIG_REF_NAME==mb_final_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/mb_final/ip/mb_final_hdmi_text_controller_0_0/mb_final_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_final_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_final_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: d:/UIUC/26Spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/mb_final_ooc.xdc
