# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.srcs/sources_1/bd/audio_control/ip/audio_control_dlmb_bram_if_cntlr_1/audio_control_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'audio_control_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/bd/audio_control/ip/audio_control_dlmb_bram_if_cntlr_1/audio_control_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_control_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.srcs/sources_1/bd/audio_control/ip/audio_control_dlmb_bram_if_cntlr_1/audio_control_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'audio_control_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/bd/audio_control/ip/audio_control_dlmb_bram_if_cntlr_1/audio_control_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_control_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
