# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UIUC/26Spring/ECE385/Final_Project/final_project/final_project.srcs/sources_1/bd/mb_final/ip/mb_final_xbar_1/mb_final_xbar_1.xci
# IP: The module: 'mb_final_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UIUC/26Spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_xbar_1/mb_final_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/UIUC/26Spring/ECE385/Final_Project/final_project/final_project.srcs/sources_1/bd/mb_final/ip/mb_final_xbar_1/mb_final_xbar_1.xci
# IP: The module: 'mb_final_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UIUC/26Spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_xbar_1/mb_final_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
