# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Module/central_constraint.xdc

# Block Designs: bd/audio_control/audio_control.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control || ORIG_REF_NAME==audio_control} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_axi_uartlite_0_0/audio_control_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_axi_uartlite_0_0 || ORIG_REF_NAME==audio_control_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_axi_uartlite_1_0/audio_control_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_axi_uartlite_1_0 || ORIG_REF_NAME==audio_control_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_axi_gpio_0_0/audio_control_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_axi_gpio_0_0 || ORIG_REF_NAME==audio_control_axi_gpio_0_0} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_microblaze_0_1/audio_control_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_microblaze_0_1 || ORIG_REF_NAME==audio_control_microblaze_0_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_dlmb_v10_1/audio_control_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_dlmb_v10_1 || ORIG_REF_NAME==audio_control_dlmb_v10_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_ilmb_v10_1/audio_control_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_ilmb_v10_1 || ORIG_REF_NAME==audio_control_ilmb_v10_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_dlmb_bram_if_cntlr_1/audio_control_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==audio_control_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_ilmb_bram_if_cntlr_1/audio_control_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==audio_control_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_lmb_bram_1/audio_control_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_lmb_bram_1 || ORIG_REF_NAME==audio_control_lmb_bram_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_xbar_1/audio_control_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_xbar_1 || ORIG_REF_NAME==audio_control_xbar_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_microblaze_0_axi_periph_1/audio_control_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_microblaze_0_axi_periph_1 || ORIG_REF_NAME==audio_control_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_microblaze_0_axi_intc_1/audio_control_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_microblaze_0_axi_intc_1 || ORIG_REF_NAME==audio_control_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_microblaze_0_xlconcat_1/audio_control_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_microblaze_0_xlconcat_1 || ORIG_REF_NAME==audio_control_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_mdm_1_1/audio_control_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_mdm_1_1 || ORIG_REF_NAME==audio_control_mdm_1_1} -quiet] -quiet

# IP: bd/audio_control/ip/audio_control_rst_clk_100MHz_100M_0/audio_control_rst_clk_100MHz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_control_rst_clk_100MHz_100M_0 || ORIG_REF_NAME==audio_control_rst_clk_100MHz_100M_0} -quiet] -quiet

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/bd/audio_control/audio_control_ooc.xdc
