# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.srcs/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4.xci
# IP: The module: 'mb_final_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.srcs/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4.xci
# IP: The module: 'mb_final_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UIUC/26spring/ECE385/Final_Project/final_project/final_project.gen/sources_1/bd/mb_final/ip/mb_final_axi_gpio_0_4/mb_final_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_final_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
