# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.srcs/sources_1/ip/BGM_rom/BGM_rom.xci
# IP: The module: 'BGM_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/BGM_rom/BGM_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BGM_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.srcs/sources_1/ip/BGM_rom/BGM_rom.xci
# IP: The module: 'BGM_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/BGM_rom/BGM_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BGM_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
