# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.srcs/sources_1/ip/audio_clk/audio_clk.xci
# IP: The module: 'audio_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/audio_clk/audio_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_clk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/audio_clk/audio_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/audio_clk/audio_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.srcs/sources_1/ip/audio_clk/audio_clk.xci
# IP: The module: 'audio_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/audio_clk/audio_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/audio_clk/audio_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/luke/University/regular_course/Sp2026/ECE_385/LAB/Final_Project/audio_test/audio_test.gen/sources_1/ip/audio_clk/audio_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
